### ISSUE TITLE
Where can I download MacOS Sonoma 14.3.1 

### ISSUE THREAD

**Issue by razvan114** [vsta2018/hackintosh#2]
I have the same laptop as you and recently i got into hackintosh but had a lot of trubble installing macOS Sonoma  until i found this githup repo, but i am wandering where can I download thjs mac os version and how can i install it.

**Comment by vsta2018** [comment]
> I have the same laptop as you and recently i got into hackintosh but had a lot of trubble installing macOS Sonoma until i found this githup repo, but i am wandering where can I download thjs mac os version and how can i install it.

Hello there, and welcome to HackIntosh
 - It'd be easiest to hack when you already had another hack or a real Mac to create the installation media. I believe it's doable in Windows (but I never tried, since I got my own Mac), and Dortania Opencore Guide (https://dortania.github.io/OpenCore-Install-Guide/) is my bible. You'd have more chance of success if you follow it closely and not losely using my efi, you should follow the guide closely and based on my efi, start with the minimum requirements (as per the guide) to get it to install first, then expand to more options at later runs.
 - Mr. MacIntosh website (https://mrmacintosh.com/) is where you can download the macOS image files
 - Once you got it to install, remember to backup. CloneZilla is what I use, which saves me a lot of time for later runs
 
 I wish you luck and Happy HackIntosh
